spring:
  application:
    name: Projectboard

  datasource:
    url: jdbc:postgresql://localhost:5432/projectboard
    username: postgres
    password: Wompler42!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
